import test from 'node:test';
import assert from 'node:assert/strict';
import { names, emptyState, calculate, convert, money, putExpense, deleteExpense, addTransfer, setBalance, validateState, type Expense } from '../src/domain/accounting.ts';
import { LocalTripRepository } from '../src/data/repository.ts';
function fixture() { const s = emptyState(); for(const n of names) s.people[n] = { initial: 1000000, allocated: 500000 }; return s; }
function expense(overrides: Partial<Expense> = {}): Expense { return { id:'expense1',phase:'during',payer:'김재영',amount:'100',currency:'CNY',rate:'205',krw:0,description:'공통 식사',date:'2026-10-07T12:00',memo:'',...overrides }; }
test('최초 지급, 배분, 공통 보유금 및 전체 보유액',()=>{ const c=calculate(fixture()); assert.equal(c.initial,6000000);assert.equal(c.allocated,3000000);assert.equal(c.pool,3000000);assert.equal(c.total,6000000);assert.equal(c.difference,0); });
test('출발 전 지출은 개인 결제잔액에 차감되지 않는다',()=>{const c=calculate(putExpense(fixture(),expense({phase:'before',currency:'KRW',amount:'1000000'})));assert.equal(c.before,1000000);assert.equal(c.departure,5000000);assert.equal(c.pool,2000000);assert.equal(c.people[2].balance,500000);assert.equal(c.total,5000000);assert.equal(c.difference,0);});
test('CNY 환산은 소수 정밀도 및 원단위 반올림을 보장한다',()=>{assert.equal(convert('100','CNY','205'),20500);assert.equal(convert('0.10','CNY','205'),21);assert.equal(convert('1.23','CNY','205.1234'),252);assert.equal(money('0'),0);assert.throws(()=>convert('1.234','CNY','205'));assert.throws(()=>money('1.5'));assert.throws(()=>convert('-10','KRW','205'));assert.throws(()=>convert('0','KRW','205'));});
test('공통지출 등록은 결제자 잔액과 전체 잔액을 함께 차감한다',()=>{const c=calculate(putExpense(fixture(),expense()));assert.equal(c.during,20500);assert.equal(c.people[2].spent,20500);assert.equal(c.people[2].balance,479500);assert.equal(c.total,5979500);assert.equal(c.expected,c.total);});
test('추가 지급은 자금 위치 이동이며 총액 불변이다',()=>{const s=fixture();const next=addTransfer(s,{id:'transfer1',person:'강병우',krw:300000,date:'2026-10-07T13:00',memo:''});const c=calculate(next);assert.equal(c.people[3].balance,800000);assert.equal(c.pool,2700000);assert.equal(c.total,calculate(s).total);assert.equal(c.difference,0);assert.throws(()=>addTransfer(next,{id:'x',person:'강병우',krw:3000000,date:'2026-10-07T13:00',memo:''}));});
test('금액 및 결제자 수정은 이전 거래를 원복하여 재계산한다',()=>{let s=putExpense(fixture(),expense());s=putExpense(s,expense({payer:'강병우',amount:'200'}));const c=calculate(s);assert.equal(s.expenses.length,1);assert.equal(c.people[2].balance,500000);assert.equal(c.people[3].balance,459000);assert.equal(c.during,41000);assert.equal(c.difference,0);});
test('지출 삭제는 개인잔액과 전체금액을 복원한다',()=>{const s=deleteExpense(putExpense(fixture(),expense()),'expense1');assert.deepEqual(calculate(s),calculate(fixture()));});
test('환율 설정 변경은 과거 거래에 영향을 주지 않는다',()=>{const s=putExpense(fixture(),expense());s.rate='220';assert.equal(s.expenses[0].rate,'205');assert.equal(calculate(s).during,20500);});
test('잔액 직접 수정은 조정 이력을 남기고 정산 차이를 나타낸다',()=>{const s=setBalance(fixture(),'김재영',400000,'adjust1','2026-10-07T13:00','현재 현금 확인');const c=calculate(s);assert.equal(c.people[2].balance,400000);assert.equal(c.difference,-100000);assert.equal(s.adjustments[0].krw,-100000);});
test('반복 거래, 수정 및 삭제 후 불변조건',()=>{let s=fixture();for(let i=0;i<100;i++){s=putExpense(s,expense({id:`e${i}`,payer:names[i%6],amount:String(i+1)}));assert.equal(calculate(s).difference,0);}for(let i=0;i<50;i++){s=deleteExpense(s,`e${i}`);assert.equal(calculate(s).difference,0);}s=addTransfer(s,{id:'t1',person:'이사장',krw:250000,date:'2026-10-07T13:00',memo:''});assert.equal(calculate(s).difference,0);});
test('로컬 저장소 재로드 및 손상 데이터 검출',()=>{const values=new Map<string,string>();const storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>values.set(k,v)} as unknown as Storage;const repo=new LocalTripRepository(storage);const s=putExpense(fixture(),expense());repo.save(s);assert.deepEqual(repo.load(),s);values.set('shanghai-trip-expense:v1','broken');assert.throws(()=>repo.load());assert.throws(()=>validateState({...s,expenses:[{...s.expenses[0],krw:1}]}));});
test('합계 범위 초과, 중복 거래 및 잘못된 설정 검출',()=>{const s=fixture();for(const n of names)s.people[n].initial=Number.MAX_SAFE_INTEGER;assert.throws(()=>calculate(s));assert.throws(()=>validateState({...fixture(),rate:'0'}));const next=putExpense(fixture(),expense());assert.throws(()=>validateState({...next,expenses:[next.expenses[0],next.expenses[0]]}));});
