import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { names, emptyState, calculate, convert, money, putExpense, deleteExpense, addTransfer, setBalance, validateState, type State, type Expense, type Person } from './domain/accounting';
import { useTripData } from './data/useTripData';
import './style.css';
const won = (n: number) => `${n.toLocaleString('ko-KR')}원`;
const now = () => { const d = new Date(); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };
const id = () => crypto.randomUUID();
function App() {
 const {s,loaded,loading,busy,uncertain,error,setError,status,refresh,perform,refreshEpoch} = useTripData();
 const [tab,setTab]=useState('홈');
 const [expense, setExpense] = useState<Expense | null>(null), [personAction, setPersonAction] = useState<{ person: Person; type: 'transfer' | 'balance' } | null>(null), [report, setReport] = useState(false);
 const c = calculate(s);
 function openExpense(phase: Expense['phase']) { setExpense({ id: id(), phase, payer: '김재영', amount: '', currency: 'CNY', rate: s.rate, krw: 0, description: '', date: now(), memo: '' }); }
 function backup() { const a = document.createElement('a'); const url = URL.createObjectURL(new Blob([JSON.stringify(s, null, 2)], { type: 'application/json' })); a.href = url; a.download = 'shanghai-trip-expense-backup.json'; a.click(); URL.revokeObjectURL(url); }
 const integrity = <div className={`integrity ${c.difference ? 'bad' : ''}`}>{c.difference ? `⚠ 정산 불일치 · 차이 ${won(c.difference)}` : '✓ 자금 정합성 정상'}<small>최초 지급 − 모든 공통지출 = {won(c.expected)}</small></div>;
 const expenseList = (items: Expense[]) => items.length ? <div className="list">{[...items].sort((a,b) => b.date.localeCompare(a.date)).map(e => <article key={e.id} className="expense"><div><strong>{e.description}</strong><small>{e.date.replace('T', ' ')} · {e.payer} · {e.phase === 'before' ? '출발 전' : '출장 중'}</small><small>{e.amount} {e.currency}{e.currency === 'CNY' && ` · 적용환율 ${e.rate}`}{e.memo && ` · ${e.memo}`}</small></div><div className="right"><strong>{won(e.krw)}</strong><div><button disabled={busy||uncertain||loading||!loaded} className="text" onClick={() => setExpense(e)}>수정</button><button disabled={busy||uncertain||loading||!loaded} className="text danger" onClick={() => { if (confirm(`‘${e.description}’ 지출을 삭제할까요? 관련 잔액이 재계산됩니다.`)) perform((s) => deleteExpense(s, e.id)); }}>삭제</button></div></div></article>)}</div> : <p className="empty">등록된 공통지출이 없습니다.</p>;
 return <><header><div className="brand">S<span>상하이 출장</span></div><div className="shared-tools"><span className="local">Google Sheets 공유</span><button aria-label="공유 데이터 새로고침" disabled={busy||uncertain||loading} onClick={()=>void refresh()}>↻</button></div></header><main className={tab === '홈' && !report ? 'home-page' : undefined}>{(tab !== '홈' || report) && <div className="pagehead"><div><p className="eyebrow">출장 자금 관리</p><h1>{report ? '전체 정산표' : tab}</h1></div><span className="admin">관리자 김재영</span></div>}{status && <div role="status" className="save-status">{status}</div>}{uncertain && !expense && !personAction && <button disabled={busy} onClick={()=>void perform((s)=>s)}>저장 재시도</button>}{error && <div role="alert" className="error">{error}<button disabled={busy||uncertain||loading||!loaded} className="text" onClick={() => setError('')}>닫기</button></div>}
 {!loaded ? <section className="loading-panel" role="status"><p>{loading ? '데이터 불러오는 중...' : '공유 데이터를 불러오지 못했습니다.'}</p>{!loading && <button disabled={loading} onClick={()=>void refresh()}>다시 시도</button>}</section> : <div className="data-content" aria-busy={busy||loading}>{loading && <p role="status" className="note">데이터 불러오는 중...</p>}{report ? <><div className="actions"><button disabled={busy||uncertain||loading||!loaded} onClick={() => setReport(false)}>← 자금현황</button><button disabled={busy||uncertain||loading||!loaded} onClick={() => window.print()}>인쇄 / PDF 저장</button></div><section><h2>{s.trip.name}</h2><p>{s.trip.start || '기간 미설정'} {s.trip.end && `~ ${s.trip.end}`}</p><div className="stats">{[['최초 출장여비', c.initial], ['출발 전 공통지출', c.before], ['출장 중 공통지출', c.during], ['총 공통지출', c.before+c.during], ['최종 개인 보유액', c.personal], ['최종 공통 보유금', c.pool], ['최종 전체 보유액', c.total]].map(([label,n]) => <div key={label}><small>{label}</small><strong>{won(n as number)}</strong></div>)}</div>{integrity}</section><section><h2>개인별 정산</h2><div className="tablewrap"><table><thead><tr>{['이름','최초 지급','실제 배분','추가 지급','공통비 결제','잔액 조정','최종 보유액'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{c.people.map(p=><tr key={p.name}><td>{p.name}</td>{[p.initial,p.allocated,p.extra,p.spent,p.adjustment,p.balance].map((n,i)=><td key={i}>{won(n)}</td>)}</tr>)}</tbody></table></div></section><section><h2>공통지출 상세</h2>{expenseList(s.expenses)}</section><section><h2>추가 지급 및 잔액 조정 기록</h2>{[...s.transfers.map(t=>({...t, kind:'추가 지급'})),...s.adjustments.map(t=>({...t,kind:'잔액 조정'}))].map(t=><p key={t.id}>{t.date.replace('T',' ')} · {t.person} · {t.kind} · {won(t.krw)} · {t.memo || '메모 없음'}</p>)}</section></> : <>
 {tab === '홈' && <><section className="hero"><span>현재 전체 보유액</span><h2>{won(c.total)}</h2><p>개인 보유액과 미배분 공통 보유금의 합계</p><button disabled={busy||uncertain||loading||!loaded} className="primary light home-expense-action" onClick={()=>openExpense('during')}>＋ 공통지출 등록</button></section><section><div className="sectionhead"><h2>최근 공통지출</h2><button disabled={busy||uncertain||loading||!loaded} className="text" onClick={()=>setTab('자금현황')}>전체 보기 →</button></div>{expenseList([...s.expenses].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5))}</section></>}
 {tab === '개인잔액' && <><p className="note">미배분 공통 보유금 {won(c.pool)} · 잔액 경고 기준 {won(s.threshold)}</p><div className="people">{c.people.map(p=><section key={p.name}><div className="sectionhead"><h2>{p.name}</h2>{p.balance<=s.threshold && <span className="warning">⚠ 잔액 부족</span>}</div><div className={`balance ${p.balance<0?'negative':''}`}>{won(p.balance)}</div><dl>{[['최초 실제 배분',p.allocated],['추가 지급',p.extra],['공통비 결제 누계',p.spent],['잔액 조정',p.adjustment]].map(([label,n])=><div key={label}><dt>{label}</dt><dd>{won(n as number)}</dd></div>)}</dl><div className="actions"><button disabled={busy||uncertain||loading||!loaded} className="primary" onClick={()=>setPersonAction({person:p.name,type:'transfer'})}>추가 지급</button><button disabled={busy||uncertain||loading||!loaded} onClick={()=>setPersonAction({person:p.name,type:'balance'})}>잔액 수정</button></div></section>)}</div><section><h2>추가 지급 기록</h2>{s.transfers.length ? [...s.transfers].reverse().map(t=><article className="expense" key={t.id}><div><strong>{t.person}</strong><small>{t.date.replace('T',' ')} · {t.memo || '메모 없음'}</small></div><div><strong>{won(t.krw)}</strong><button disabled={busy||uncertain||loading||!loaded} className="text danger" onClick={()=>{if(confirm('이 추가 지급 기록을 취소할까요?')) perform((s)=>({...s,transfers:s.transfers.filter(x=>x.id!==t.id)}));}}>취소</button></div></article>) : <p className="empty">추가 지급 기록이 없습니다.</p>}</section></>}
 {tab === '자금현황' && <><section><div className="sectionhead"><h2>전체 자금 흐름</h2><button disabled={busy||uncertain||loading||!loaded} className="text" onClick={()=>setReport(true)}>전체 정산표 →</button></div><dl className="flow">{[['최초 지급 총액',c.initial],['− 출발 전 공통지출',c.before],['출발 시 보유자금',c.departure],['개인 배분 합계',c.allocated],['추가 지급 합계',c.transferred],['현재 미배분 공통 보유금',c.pool],['출장 중 공통지출',c.during],['현재 개인 보유액 합계',c.personal],['현재 전체 보유액',c.total]].map(([label,n])=><div key={label}><dt>{label}</dt><dd className={(n as number)<0?'negative':''}>{won(n as number)}</dd></div>)}</dl>{integrity}{c.pool<0 && <p className="error">공통 보유금이 음수입니다. 최초 지급액, 배분액과 출발 전 지출을 확인하세요.</p>}</section><section><h2>6명 최초 지급 상세</h2><dl>{c.people.map(p=><div key={p.name}><dt>{p.name}</dt><dd>{won(p.initial)}</dd></div>)}</dl></section><section><div className="sectionhead"><h2>출발 전 공통지출</h2><button disabled={busy||uncertain||loading||!loaded} onClick={()=>openExpense('before')}>＋ 등록</button></div>{expenseList(s.expenses.filter(e=>e.phase==='before'))}</section><section><div className="sectionhead"><h2>출장 중 공통지출</h2><button disabled={busy||uncertain||loading||!loaded} onClick={()=>openExpense('during')}>＋ 등록</button></div>{expenseList(s.expenses.filter(e=>e.phase==='during'))}</section></>}
 {tab === '설정' && <><section><h2>출장 및 자금 설정</h2><form key={refreshEpoch} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);perform((s)=>{const next={...s,trip:{name:String(f.get('trip')),start:String(f.get('start')),end:String(f.get('end'))},rate:String(f.get('rate')),threshold:money(String(f.get('threshold'))),people:{...s.people}};if(next.trip.start && next.trip.end && next.trip.start>next.trip.end)throw new Error('출장 종료일은 시작일 이후여야 합니다.');for(const n of names)next.people[n]={initial:money(String(f.get(`${n}-initial`))),allocated:money(String(f.get(`${n}-allocated`)))};return validateState(next);});}}><fieldset className="form-fields" disabled={busy||uncertain||loading}><label>출장명<input name="trip" required defaultValue={s.trip.name}/></label><div className="two"><label>시작일<input name="start" type="date" defaultValue={s.trip.start}/></label><label>종료일<input name="end" type="date" defaultValue={s.trip.end}/></label></div><div className="two"><label>1 CNY 기준환율 (KRW)<input name="rate" inputMode="decimal" required defaultValue={s.rate}/></label><label>잔액 경고 기준 (KRW)<input name="threshold" inputMode="numeric" required defaultValue={s.threshold}/></label></div><p className="note">기준환율 변경은 새 지출에 적용됩니다. 과거 지출의 환율과 환산금액은 보존됩니다.</p><h3>최초 지급액 / 실제 배분액</h3>{names.map(n=><fieldset key={n}><legend>{n}</legend><div className="two"><label>최초 지급액 (KRW)<input name={`${n}-initial`} required inputMode="numeric" defaultValue={s.people[n].initial}/></label><label>실제 배분액 (KRW)<input name={`${n}-allocated`} required inputMode="numeric" defaultValue={s.people[n].allocated}/></label></div></fieldset>)}</fieldset><button disabled={busy||loading} className="primary" type="submit">{busy ? '저장 중...' : uncertain ? '저장 재시도' : '설정 저장'}</button></form></section><section><h2>데이터 백업</h2><p className="note">Google Sheet가 공용 원본입니다. JSON 백업은 현재 조회된 공유 데이터를 내려받습니다. 복원은 공유 데이터 전체를 교체하므로 팀원에게 먼저 알려주세요.</p><div className="actions"><button onClick={backup} disabled={!loaded||busy||uncertain||loading}>JSON 백업 다운로드</button><label className="filebutton">백업 복원<input disabled={busy||uncertain||loading} type="file" accept="application/json,.json" onChange={async e=>{const input=e.currentTarget;const file=input.files?.[0];if(!file)return;try{const restored=validateState(JSON.parse(await file.text()));if(confirm('공유 Google Sheet 전체 데이터를 백업으로 교체할까요? 모든 팀원에게 반영됩니다.')){const success=await perform(()=>restored,true);if(!success)input.value='';}}catch(err){setError((err as Error).message);}input.value='';}}/></label></div></section></>}
 </>}</div>}</main><nav aria-label="주 메뉴">{['홈','개인잔액','자금현황','설정'].map((t,i)=><button disabled={busy||uncertain||loading||!loaded} key={t} className={tab===t&&!report?'active':''} onClick={()=>{setTab(t);setReport(false);}}><span>{['⌂','♙','▤','⚙'][i]}</span>{t}</button>)}</nav>
 {expense && <div className="overlay"><section role="dialog" aria-modal="true" aria-labelledby="expense-title" className="sheet"><div className="sectionhead"><h2 id="expense-title">{s.expenses.some(e=>e.id===expense.id)?'공통지출 수정':'공통지출 등록'}</h2><button disabled={busy||uncertain||loading||!loaded} aria-label="닫기" onClick={()=>setExpense(null)}>✕</button></div><div role="alert" className={error ? "error" : ""}>{error}</div><form onSubmit={async e=>{e.preventDefault();if(await perform((s)=>putExpense(s,expense)))setExpense(null);}}><fieldset className="form-fields" disabled={busy||uncertain||loading}><div className="two"><label>구분<select value={expense.phase} onChange={e=>setExpense({...expense,phase:e.target.value as Expense['phase']})}><option value="during">출장 중 공통지출</option><option value="before">출발 전 공통지출</option></select></label><label>결제자<select value={expense.payer} onChange={e=>setExpense({...expense,payer:e.target.value as Person})}>{names.map(n=><option key={n}>{n}</option>)}</select></label></div><div className="two"><label>금액<input autoFocus inputMode="decimal" required value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></label><label>통화<select value={expense.currency} onChange={e=>setExpense({...expense,currency:e.target.value as Expense['currency']})}><option>CNY</option><option>KRW</option></select></label></div>{expense.currency==='CNY' && <label>적용 환율 (1 CNY = KRW)<input inputMode="decimal" required value={expense.rate} onChange={e=>setExpense({...expense,rate:e.target.value})}/></label>}<p className="preview">KRW 환산금액: {(()=>{try{return won(convert(expense.amount,expense.currency,expense.rate));}catch{return '금액을 확인하세요';}})()}</p><label>사용내용<input required value={expense.description} onChange={e=>setExpense({...expense,description:e.target.value})} placeholder="예: 호텔 선결제, 공통 식사"/></label><label>날짜 / 시간<input type="datetime-local" required value={expense.date} onChange={e=>setExpense({...expense,date:e.target.value})}/></label><label>메모 (선택)<textarea value={expense.memo} onChange={e=>setExpense({...expense,memo:e.target.value})}/></label><p className="note">{expense.phase==='before'?'출발 전 지출은 출발 시 자금에서 차감합니다. 개인 배분잔액에서는 차감하지 않습니다.':'출장 중 지출은 선택한 결제자의 개인잔액에서 차감합니다.'}</p></fieldset><button disabled={busy||loading} className="primary full">{busy ? '저장 중...' : uncertain ? '저장 재시도' : '지출 저장'}</button></form></section></div>}
 {personAction && <div className="overlay"><section className="sheet" role="dialog" aria-modal="true" aria-labelledby="person-title"><div className="sectionhead"><h2 id="person-title">{personAction.person} · {personAction.type==='transfer'?'추가 지급':'현재잔액 수정'}</h2><button disabled={busy||uncertain||loading||!loaded} aria-label="닫기" onClick={()=>setPersonAction(null)}>✕</button></div><p className="note">{personAction.type==='transfer'?`공통 보유금 ${won(c.pool)}에서 이동하며 전체 보유액은 변하지 않습니다.`:'현재잔액 수정은 조정 기록을 남기며 정산 불일치가 발생할 수 있습니다.'}</p><div role="alert" className={error ? "error" : ""}>{error}</div><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const ok=await perform((s)=>personAction.type==='transfer'?addTransfer(s,{id:id(),person:personAction.person,krw:money(String(f.get('amount'))),date:String(f.get('date')),memo:String(f.get('memo'))}):setBalance(s,personAction.person,money(String(f.get('amount'))),id(),String(f.get('date')),String(f.get('memo'))));if(ok)setPersonAction(null);}}><fieldset className="form-fields" disabled={busy||uncertain||loading}><label>{personAction.type==='transfer'?'추가 지급액':'수정 후 현재잔액'} (KRW)<input autoFocus required inputMode="numeric" name="amount" defaultValue={personAction.type==='balance'?c.people.find(p=>p.name===personAction.person)!.balance:''}/></label><label>날짜 / 시간<input type="datetime-local" name="date" required defaultValue={now()}/></label><label>{personAction.type==='balance'?'수정 사유 (필수)':'메모 (선택)'}<textarea name="memo" required={personAction.type==='balance'}/></label></fieldset><button disabled={busy||loading} className="primary full">{busy ? '저장 중...' : uncertain ? '저장 재시도' : '저장'}</button></form></section></div>}
 </>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);


